/**
 * ESLint 9 Flat Config - Project-Local Customizations
 *
 * Add project-specific ESLint rules here. This file is create-only,
 * meaning Lisa will create it but never overwrite your customizations.
 *
 * Example:
 * ```ts
 * export default [
 *   {
 *     files: ["src/legacy/**"],
 *     rules: {
 *       "@typescript-eslint/no-explicit-any": "off",
 *     },
 *   },
 * ];
 * ```
 *
 * @see https://eslint.org/docs/latest/use/configure/configuration-files-new
 * @module eslint.config.local
 */
export default [
  {
    // `src/assets.ts` is GENERATED by scripts/pack-assets.mjs (DO NOT EDIT); its
    // typed key table is one entry per committed frame, so it grows with the art
    // catalog. The per-file line budget does not apply to this machine-authored
    // manifest — every other rule still does.
    files: ["src/assets.ts"],
    rules: {
      "max-lines": "off",
    },
  },
  {
    // The published enforce-statement-order rule tightened (Lisa 2.189.18+) to
    // check every function body and awaited call, reddening pre-existing source
    // that predates the change. Relax it back to its prior scope here — a
    // config-only opt-out that preserves existing behavior — rather than
    // hand-refactoring proven code. Mirrors Lisa's own eslint.config.local.ts.
    rules: {
      "code-organization/enforce-statement-order": [
        "error",
        { checkAllFunctionBodies: false, checkAwaitedCalls: false },
      ],
    },
  },
];
