/**
 * The pure two-resource economy: per-turn Anima (AP) regeneration and the
 * resource cost / affordability of an acting turn. A Craft spell spends the
 * actor's AP (the Anima pool); a Bind summon spends grist from the single shared
 * party wallet — the "spend the world to win?" tension from the
 * [combat-spec](../../../wiki/design/combat-spec.md) "two resources in numbers"
 * and the [economy-spec](../../../wiki/design/economy-spec.md). Every function
 * here is a total function of explicit inputs — no Phaser, no I/O, no RNG,
 * nothing ambient — so the reducer that calls them stays deterministic.
 * @module logic/combat/resource
 */
import { BOUNDS, SPELLS, type SpellDef } from "../../content";
import { ActionKinds, type BattleAction, type Combatant } from "./types";

/**
 * First-pass two-resource tuning (combat-spec / economy-spec). AP regenerates
 * slowly each turn; grist is the shared wallet only the strongest actions (Bind,
 * top-tier Render, revive) spend. Constants are Phase-1 targets — the *shapes*
 * (AP regen per turn, AP for Craft, grist for Bind) are the contract.
 */
export const ResourceTuning = {
  /** Anima (AP) regenerated by a combatant each turn (ATB tick), clamped to max. */
  apRegenPerTurn: 2,
} as const;

/** The resources an action spends: AP from the actor, grist from the shared pool. */
export interface ActionCost {
  /** Anima spent from the actor's AP pool. */
  readonly ap: number;
  /** Grist spent from the shared party wallet. */
  readonly grist: number;
}

/** The zero cost — a non-spending action (Strike, Defend, a tick). */
const FREE: ActionCost = { ap: 0, grist: 0 };

/**
 * Regenerate one turn's Anima for a combatant: add
 * {@link ResourceTuning.apRegenPerTurn}, clamped to the combatant's max AP
 * (`stats.ap`). At or above max it is a no-op, returning the same object so a
 * full party's tick keeps structural sharing.
 * @param combatant - The combatant whose AP regenerates.
 * @returns The combatant with regenerated AP (or the same object when at max).
 */
export function regenAp(combatant: Combatant): Combatant {
  const ap = Math.min(
    combatant.ap + ResourceTuning.apRegenPerTurn,
    combatant.stats.ap
  );
  return ap === combatant.ap ? combatant : { ...combatant, ap };
}

/**
 * The castable spell a Craft action names, or null when the id is absent/unknown.
 * @param id - The action's spell id.
 * @returns The spell definition, or null.
 */
export function craftSpellById(id: string | undefined): SpellDef | null {
  if (id === undefined) {
    return null;
  }
  return (SPELLS as Record<string, SpellDef>)[id] ?? null;
}

/**
 * The grist-costed Bind summon a Bind action names, or null when absent/unknown.
 * Binds live inline on their shard ({@link BOUNDS}.*.bind), not in {@link SPELLS}.
 * @param id - The action's Bind id.
 * @returns The Bind spell definition, or null.
 */
function bindSpellById(id: string | undefined): SpellDef | null {
  if (id === undefined) {
    return null;
  }
  const owner = Object.values(BOUNDS).find(bound => bound.bind.id === id);
  return owner ? owner.bind : null;
}

/**
 * Resolve the spell/Bind def an action draws its cost from: a Craft's castable
 * spell, a Bind's summon, or null for any non-resourced kind.
 * @param action - The action to resolve.
 * @returns The spell/Bind definition, or null.
 */
function spellForAction(action: BattleAction): SpellDef | null {
  if (action.kind === ActionKinds.craft) {
    return craftSpellById(action.id);
  }
  if (action.kind === ActionKinds.bind) {
    return bindSpellById(action.id);
  }
  return null;
}

/**
 * The resource cost of an action: a defined Craft costs its `apCost` (and any
 * `gristCost`); a defined Bind costs its `gristCost` (and any `apCost`); every
 * other kind — and any unknown spell/Bind id — is {@link FREE}.
 * @param action - The action to price.
 * @returns The AP + grist the action spends.
 */
export function actionCost(action: BattleAction): ActionCost {
  const spell = spellForAction(action);
  return spell ? { ap: spell.apCost, grist: spell.gristCost ?? 0 } : FREE;
}

/**
 * Whether an action's cost can be paid: the actor has at least the AP and the
 * shared pool has at least the grist.
 * @param actorAp - The acting combatant's current AP.
 * @param pool - The shared party grist pool.
 * @param cost - The action's resolved cost.
 * @returns True when both resources cover the cost.
 */
export function canAfford(
  actorAp: number,
  pool: number,
  cost: ActionCost
): boolean {
  return actorAp >= cost.ap && pool >= cost.grist;
}
